version: "3.1"
services:
    nginx:
      image: nginx:alpine
      working_dir: /app
      volumes:
          - .:/app
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php:
      environment:
        XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1"
        PHP_IDE_CONFIG: "serverName=localhost"
      build: docker/php-fpm
      working_dir: /app
      volumes:
        - .:/app
    mysql:
      image: mysql:latest
      volumes:
        - app-mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=app
      ports:
        - "3307:3306"
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - 8086:80
      links:
        - mysql
      environment:
        PMA_HOST: mysql
    swagger:
      image: swaggerapi/swagger-ui:latest
      ports:
        - 8087:8080
      environment:
        API_URL: http://localhost:8080/docs/json
volumes:
  app-mysql: